FROM python:3.5
RUN pip install --upgrade pip && \
    pip install  numpy==1.11.1 && \
    pip install  scipy==0.17.1 && \
    pip install  scikit-learn==0.17.1 && \
    pip install  pandas==0.18.1 && \
    pip install  pyramid==1.7 && \
	pip install  pyramid-jinja2==2.6.2 && \
	pip install  pyramid-debugtoolbar==3.0.2 && \
	pip install  pyramid_debugtoolbar && \
	pip install  pyramid-tm==0.12.1 && \
	pip install  authomatic==0.1.0.post1 && \
	pip install  cornice==1.2.1 && \
	pip install  sqlalchemy==1.1.0b2 && \
	pip install  transaction==1.6.1 && \
	pip install  zope.sqlalchemy==0.7.7 && \
	pip install  waitress==1.0a2 && \
	pip install  psycopg2==2.6.2 && \
	pip install  python-dateutil==2.5.3 && \
	pip install  git+https://github.com/mobolic/facebook-sdk.git#egg=facebook-sdk && \
	pip install  nose==1.3.7


LABEL Description="base image for sosilee"